stages:
  - build
  - test

cache:
  key: new_cache
  paths:
    - .m2/repository/

build:
  image: maven:3-jdk-8
  stage: build
  tags: [moonways-runner, Joule]
  script: |-
    /bin/bash bridgenet -fb
