stages:
  - build
cache:
  paths:
    - $CI_PROJECT_DIR/.m2/repository

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

build:
  image: maven:3-jdk-8
  stage: build
  interruptible: true
  tags:
    - $CI_RUNNER_TAG
  script:
    |-
    /bin/bash bridgenet -fb
  artifacts:
    when: always
    expire_in: 5 days
    paths:
      - $CI_PROJECT_DIR/*