stages:
  - build
  - test

build:
  image: maven:3-jdk-8
  stage: build
  interruptible: true
  variables:
    MAVEN_OPTS: "-Dmaven.repo.local=/root/.m2/repository"
  tags:
    - moonways-runner
  script: bin/bash bridgenet -fb
  artifacts:
    paths:
      - $CI_PROJECT_DIR/*

unit_tests:
  image: maven:3-jdk-8
  stage: test
  interruptible: true
  variables:
    MAVEN_OPTS: "-Dmaven.repo.local=/root/.m2/repository"
  tags:
    - moonways-runner
  script: mvn clean install --file test-engine/pom.xml
