variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

stages:
  - build
#  - test

build:
  image: maven:3-jdk-8
  stage: build
  interruptible: true
  tags:
    - moonways-runner
  script: |-
    /bin/bash bridgenet -fb
    mvn test --file test-engine/pom.xml
  #artifacts:
  #  paths:
  #    - $CI_PROJECT_DIR/*

#unit_tests:
#  image: maven:3-jdk-8
#  stage: test
#  interruptible: true
#  tags:
#    - moonways-runner
#  script: mvn install --file test-engine/pom.xml
