variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
cache:
  paths:
    - $CI_PROJECT_DIR/.m2/repository

stages:
  - build
  - test

build:
  image: maven:3-jdk-8
  stage: build
  interruptible: true
  tags:
    - $CI_RUNNER_TAG
  script: #/bin/bash bridgenet build
  artifacts:
    when: always
    expire_in: 5 days
    paths:
      - $CI_PROJECT_DIR/*

test:
  image: maven:3-jdk-8
  stage: test
  interruptible: true
  tags:
    - $CI_RUNNER_TAG
  script:
    - cp -R $CI_PROJECT_DIR/.m2 $HOME
    - cd $CI_PROJECT_DIR
    - ls
    - cd /test-engine
    - ls
    - mvn test -pl test-engine
  dependencies:
    - build
  artifacts:
    when: always
    expire_in: 5 days
    paths:
      - $CI_PROJECT_DIR/*